# Generated by Django 2.0.7 on 2019-06-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=30)),
                ('imageURLaaaa', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
    ]
