# Generated by Django 2.0.7 on 2019-06-02 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imageURLaaaa',
            new_name='imageURL',
        ),
    ]
